const User = require("../models/user");
const Link = require("../models/link");

// req.profile is available because authMiddleware was called first in routes and thus req.profile was generated by attaching the result of a db query.

// hashed passwords and salt should not be sent to the frontend and thus have been changed to undefined

exports.read = (req, res) => {
  User.findOne({ _id: req.user._id }).exec((err, user) => {
    if (err) {
      res.json({
        error: "User not found",
      });
    }
    user.hashed_password = undefined;
    user.salt = undefined;
    res.json({
      user,
    });
  });
};
exports.update = (req, res) => {
  const { name, password } = req.body;

  switch (true) {
    case password && password.length < 6:
      return res.status(400).json({
        error: "Password must be at least 6 characters long",
      });
  }

  User.findOneAndUpdate(
    { _id: req.user._id },
    { name, password },
    { new: true }
  ).exec((err, updated) => {
    if (err) {
      res.status(400).json({
        error: "Could not update user",
      });
    }
    updated.hashed_password = undefined;
    updated.salt = undefined;
    res.json({ user: updated, message: "Account has been updated!" });
  });
};
