// req.profile is available because authMiddleware was called first in routes and thus req.profile was generated by attaching the result of a db query.

// hashed passwords and salt should not be sent to the frontend and thus have been changed to undefined

exports.read = (req, res) => {
  req.profile.hashed_password = undefined;
  req.profile.salt = undefined;
  return res.json(req.profile);
};
